name: CI

on:
  push:
    paths-ignore:
      - ".github/dependabot.yml"
      - ".github/workflows/ssh1-image.yml"
      - "docker/Dockerfile.ssh1"
      - "LICENSE"
      - "README.md"
  pull_request:
    paths-ignore:
      - ".github/dependabot.yml"
      - ".github/workflows/ssh1-image.yml"
      - "docker/Dockerfile.ssh1"
      - "LICENSE"
      - "README.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Test
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic
      - name: Coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.out

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Build
        run: go build .
