name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Build
        run: go build .
      - name: Test
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic
      - name: Coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.out
