name: SSH1 image

on:
  push:
    paths:
      - ".github/workflows/ssh1-image.yml"
      - "docker/Dockerfile.ssh1"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker
          file: Dockerfile.ssh1
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ultram4rine/ssh1:latest
            ghcr.io/ultram4rine/ssh1:latest
